version: '3.8'

services:
  financialtracker.api:
    image: ${DOCKER_REGISTRY-}financialtrackerapi
    build:
      context: .
      dockerfile: FinancialTrackerKafkaFocused/Dockerfile
    ports:
    # - "5146:5146"      # HTTP (optional)
    - "7238:7238"
    volumes:
            - https:/https
    container_name: financialtracker.api
    networks:
      - app-net
    
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
      - Kafka__BootstrapServers=localhost:9092
      - Kafka__Topic=orders-created-topic
    depends_on:
      - kafka

  worker:
    image: notificationservice
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    container_name: notificationservice-worker
    networks:
      - app-net
    environment:
      #- DOTNET_ENVIRONMENT=Development
      # - Kafka__BootstrapServers=localhost:9092
      # - Kafka__GroupId=notification-worker-group
      # - Kafka__Topic=orders-created-topic
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    networks:
      - app-net
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

# Define the network at the bottom
networks:
  app-net:
    driver: bridge

volumes:
  https:
      #cd /c/Users/akshy/source/repos/FinancialTrackerKafkaFocused


      # get kafka topic name
  #     docker exec -it financialtrackerkafkafocused-kafka-1 kafka-topics \
  # --list \
  # --bootstrap-server localhost:9092



      # docker exec -it financialtrackerkafkafocused-kafka-1 kafka-topics --describe --topic orders-created-topic --bootstrap-server localhost:9092


# docker compose logs -f notificationservice-worker
#docker compose up --build worker


# visual studio
#Test-NetConnection -ComputerName localhost -Port 9092

# docker compose exec  financialtracker.api bash